# Generated by Django 3.2.18 on 2023-03-06 19:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('capacity', models.CharField(choices=[('DESK HQ Brooklyn House', 'DESK HQ Brooklyn House'), ('DESK HQ Dockyard Place', 'DESK HQ Dockyard Place')], max_length=50, unique=True)),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Space_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.CharField(choices=[('Day WorkStation', 'Day WorkStation'), ('Conference Room(Up to 35 seats)', 'Conference Room(Up to 35 seats)'), ('Coworking WorkStation', 'Coworking WorkStation'), ('Exclusive workstation(private)', 'Exclusive workstation(private)'), ('Training Rooms', 'Training Rooms'), ('Meeting Room(Up to 12 seats)', 'Meeting Room(Up to 12 seats)')], max_length=50, unique=True)),
                ('space', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='space_type', to='desk.work_space')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=datetime.datetime.now)),
                ('booking_duration', models.CharField(choices=[('1 Hour', '1 Hour'), ('2 Hours', '2 Hours'), ('3 Hours', '3 Hours'), ('4 Hours', '4 Hours'), ('5 Hours', '5 Hours'), ('6 Hours', '6 Hours'), ('7 Hours', '7 Hours'), ('8 Hours', '8 Hours'), ('All day', 'All day')], default='Anytime', max_length=20)),
                ('booking_time', models.CharField(choices=[('09:00 am', '09:00 am'), ('09:30 am', '09:30 am'), ('10:00 am', '10:00 am'), ('10:30 am', '10:30 am'), ('11:00 am', '11:00 am'), ('11:30 am', '11:30 am'), ('12:00 pm', '12:00 pm'), ('12:30 pm', '12:30 pm'), ('13:00 pm', '13:00 pm'), ('13:30 pm', '13:30 pm'), ('14:00 pm', '14:00 pm'), ('14:30 pm', '14:30 pm'), ('15:00 pm', '15:00 pm'), ('15:30 pm', '15:30 pm'), ('16:00 pm', '16:00 pm'), ('16:30 pm', '16:30 pm'), ('17:00 pm', '17:00 pm'), ('17:30 pm', '17:30 pm')], default='09:00 am', max_length=20)),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_booking', to=settings.AUTH_USER_MODEL)),
                ('space_booking', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='space_booking', to='desk.space_type')),
            ],
            options={
                'order_with_respect_to': 'space_booking',
            },
        ),
    ]
