# Generated by Django 3.2.18 on 2023-03-23 15:50

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('location_name', models.CharField(choices=[('DESK HQ Brooklyn House (3 STONE AVENUE LONDON SE5 2AZ)', 'DESK HQ Brooklyn House (3 STONE AVENUE LONDON SE5 2AZ)'), ('DESK HQ Dockyard Place (55 PARADE STREET LONDON E20 3YB)', 'DESK HQ Dockyard Place (55 PARADE STREET LONDON E20 3YB)')], default='DESK HQ Brooklyn House (3 STONE AVENUE LONDON SU5 2AZ)', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('Day WorkStation', 'Day WorkStation'), ('Conference Room(Up to 35 seats)', 'Conference Room(Up to 35 seats)'), ('Coworking WorkStation', 'Coworking WorkStation'), ('Exclusive workstation(private)', 'Exclusive workstation(private)'), ('Training Rooms', 'Training Rooms'), ('Meeting Room(Up to 12 seats)', 'Meeting Room(Up to 12 seats)')], default='Day WorkStation', max_length=50, unique=True)),
                ('content', models.TextField(blank=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=datetime.datetime.now)),
                ('booking_duration', models.CharField(choices=[('1 Hour', '1 Hour'), ('2 Hours', '2 Hours'), ('3 Hours', '3 Hours'), ('4 Hours', '4 Hours'), ('5 Hours', '5 Hours'), ('6 Hours', '6 Hours'), ('7 Hours', '7 Hours'), ('8 Hours', '8 Hours'), ('All day', 'All day')], default='Anytime', max_length=20)),
                ('booking_start', models.CharField(choices=[('09:00 am', '09:00 am'), ('09:30 am', '09:30 am'), ('10:00 am', '10:00 am'), ('10:30 am', '10:30 am'), ('11:00 am', '11:00 am'), ('11:30 am', '11:30 am'), ('12:00 pm', '12:00 pm'), ('12:30 pm', '12:30 pm'), ('13:00 pm', '13:00 pm'), ('13:30 pm', '13:30 pm'), ('14:00 pm', '14:00 pm'), ('14:30 pm', '14:30 pm'), ('15:00 pm', '15:00 pm'), ('15:30 pm', '15:30 pm'), ('16:00 pm', '16:00 pm'), ('16:30 pm', '16:30 pm'), ('17:00 pm', '17:00 pm'), ('17:30 pm', '17:30 pm')], default='09:00 am', max_length=20)),
                ('booking_end', models.CharField(choices=[('09:00 am', '09:00 am'), ('09:30 am', '09:30 am'), ('10:00 am', '10:00 am'), ('10:30 am', '10:30 am'), ('11:00 am', '11:00 am'), ('11:30 am', '11:30 am'), ('12:00 pm', '12:00 pm'), ('12:30 pm', '12:30 pm'), ('13:00 pm', '13:00 pm'), ('13:30 pm', '13:30 pm'), ('14:00 pm', '14:00 pm'), ('14:30 pm', '14:30 pm'), ('15:00 pm', '15:00 pm'), ('15:30 pm', '15:30 pm'), ('16:00 pm', '16:00 pm'), ('16:30 pm', '16:30 pm'), ('17:00 pm', '17:00 pm'), ('17:30 pm', '17:30 pm')], default='09:00 am', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Valid'), (1, 'Cancelled')], default=1)),
                ('approved', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desk.location')),
                ('space_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_booking', to='desk.service')),
            ],
            options={
                'ordering': ['created_on'],
                'unique_together': {('location', 'space_booking', 'booking_date', 'booking_duration', 'booking_start', 'booking_end')},
            },
        ),
    ]
