# Generated by Django 3.2.18 on 2023-03-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_space',
            new_name='Location',
        ),
    ]
