# Generated by Django 3.2.18 on 2023-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(choices=[('3 STONE AVENUE LONDON SU5 2AZ', '3 STONE Avenue London SU5 2AZ'), ('55 PARADE STREET LONDON E20 3YB', '55 Parade Street London E20 3YB')], default='', max_length=200, unique=True),
        ),
    ]
