# Generated by Django 4.1.7 on 2023-03-29 22:18

import datetime
import desk.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20230323_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 30, 22, 18, 46, 838349), validators=[desk.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(default='DESK HQ Brooklyn House (3 STONE AVENUE LONDON SE5 2AZ)', null=True, on_delete=django.db.models.deletion.CASCADE, to='desk.location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='space_booking',
            field=models.ForeignKey(default='Day WorkStation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_booking', to='desk.service'),
        ),
    ]
