# Generated by Django 3.2.18 on 2023-03-07 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_rename_work_space_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
