# Generated by Django 3.2.18 on 2023-03-17 09:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20230311_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='service',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
