# Generated by Django 3.2.18 on 2023-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20230317_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, default='hello'),
        ),
    ]
