# Generated by Django 3.2.18 on 2023-03-07 14:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20230307_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='capacity',
        ),
        migrations.AddField(
            model_name='location',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(choices=[('DESK HQ Brooklyn House', 'DESK HQ Brooklyn House'), ('DESK HQ Dockyard Place', 'DESK HQ Dockyard Place')], max_length=50, unique=True),
        ),
    ]
