# Generated by Django 3.2.18 on 2023-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20230310_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location_address',
            field=models.CharField(default='3 STONE AVENUE LONDON SU5 2AZ', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(choices=[('DESK HQ Brooklyn House', 'DESK HQ Brooklyn House'), ('DESK HQ Dockyard Place', 'DESK HQ Dockyard Place')], default='DESK HQ Brooklyn House', max_length=200),
        ),
    ]
