# Generated by Django 3.2.18 on 2023-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_auto_20230307_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Space_type',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booking_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start',
            field=models.CharField(choices=[('09:00 am', '09:00 am'), ('09:30 am', '09:30 am'), ('10:00 am', '10:00 am'), ('10:30 am', '10:30 am'), ('11:00 am', '11:00 am'), ('11:30 am', '11:30 am'), ('12:00 pm', '12:00 pm'), ('12:30 pm', '12:30 pm'), ('13:00 pm', '13:00 pm'), ('13:30 pm', '13:30 pm'), ('14:00 pm', '14:00 pm'), ('14:30 pm', '14:30 pm'), ('15:00 pm', '15:00 pm'), ('15:30 pm', '15:30 pm'), ('16:00 pm', '16:00 pm'), ('16:30 pm', '16:30 pm'), ('17:00 pm', '17:00 pm'), ('17:30 pm', '17:30 pm')], default='09:00 am', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(choices=[('DESK HQ Brooklyn House', 'DESK HQ Brooklyn House'), ('DESK HQ Dockyard Place', 'DESK HQ Dockyard Place')], default='', max_length=50, unique=True),
        ),
    ]
