# Generated by Django 3.2.18 on 2023-03-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_auto_20230317_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(choices=[('DESK HQ Brooklyn House (3 STONE AVENUE LONDON SE5 2AZ)', 'DESK HQ Brooklyn House (3 STONE AVENUE LONDON SE5 2AZ)'), ('DESK HQ Dockyard Place (55 PARADE STREET LONDON E20 3YB)', 'DESK HQ Dockyard Place (55 PARADE STREET LONDON E20 3YB)')], default='DESK HQ Brooklyn House (3 STONE AVENUE LONDON SU5 2AZ)', max_length=200),
        ),
    ]
