# Generated by Django 3.2.18 on 2023-03-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_booking_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='space_booking',
            field=models.ForeignKey(default='Day Workstation', on_delete=django.db.models.deletion.CASCADE, related_name='space_booking', to='desk.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_type', to='desk.location'),
        ),
    ]
