# Generated by Django 4.1.7 on 2023-04-07 16:10

import datetime
import desk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0008_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 8, 16, 10, 16, 192828), validators=[desk.models.validate_date]),
        ),
    ]
