# Generated by Django 4.1.7 on 2023-04-16 14:45

import datetime
import desk.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0013_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2023, 4, 17), validators=[desk.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='space_booking',
            field=models.ForeignKey(default='Day WorkStation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_bookings', to='desk.service'),
        ),
    ]
