# Generated by Django 4.1.7 on 2023-04-28 17:19

import datetime
import desk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0015_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2023, 4, 29), validators=[desk.models.validate_date]),
        ),
    ]
