# Generated by Django 4.1.7 on 2025-07-15 06:50

import datetime
import desk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0016_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2025, 7, 16), validators=[desk.models.validate_date]),
        ),
    ]
